PM_QLHS/Models/LopViewModel.cs
using PM_QLHS.Class.Dtos;

namespace PM_QLHS.Models
{
    public class LopViewModel
    {
        public int MaLop { get; set; }
        public string? TenLop { get; set; }
        public int? SiSo { get; set; }
        public int? MaKhoi { get; set; }
        public int? MaGVChuNhiem { get; set; }
        public string? ThoiKhoaBieu { get; set; }
        public string? TenKhoi { get; set; }
        public string? HoTen { get; set; }
        public PageReponResult<LopViewModel> Lops { get; set; }

        public LopViewModel()
        {
            Lops = new PageReponResult<LopViewModel>();
        }
    }
}

PM_QLHS/Controllers/LopController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using NToastNotify;
using PM_QLHS.Class.Authorization;
using PM_QLHS.Class.Dtos;
using PM_QLHS.Class.ViewModels;
using PM_QLHS.Models;
using PM_QLHS.Repository;

namespace PM_QLHS.Controllers
{
    public class LopController : Controller
    {
        private readonly ILogger<LopController> _logger;
        private readonly ILopRepository _lopRepository;
        private readonly IToastNotification _toastNotification;

        public LopController(ILogger<LopController> logger, IToastNotification toastNotification, ILopRepository lopRepository)
        {
            _logger = logger;
            _toastNotification = toastNotification;
            _lopRepository = lopRepository;
        }

        [Authorize(Role.GVu)]
        public IActionResult Index()
        {
            var data = new LopViewModel();
            var result = _lopRepository.GetAllView();

            data.Lops = result.Success ? result.Data : new PageReponResult<LopViewModel>();
            return View(data);
        }

        [HttpGet]
        public ActionResult GetALl()
        {
            var result = _lopRepository.GetAll();
            return Json(result);
        }

        [HttpGet]
        [Route("/lop/getById")]
        public IActionResult GetById(int id)
        {
            var result = _lopRepository.GetById(id);
            return Json(result);
        }

        [HttpPost]
        [Route("/lop/create")]
        public IActionResult Create(LopVm request)
        {
            var result = _lopRepository.Create(request);
            if (result.Success)
            {
                _toastNotification.AddSuccessToastMessage("Lưu dữ liệu thành công!");
            }
            else
            {
                _toastNotification.AddErrorToastMessage("Lưu dữ liệu thất bại!");
            }
            return Ok(result);
        }

        [HttpPatch]
        [Route("/lop/update")]
        public IActionResult Update(LopVm request)
        {
            if (request.MaLop <= 0)
            {
                _toastNotification.AddErrorToastMessage("Vui lòng nhập đầy đủ dữ liệu yêu cầu!!");
                return Ok(new ApiErrorResult<int>());
            }
            var result = _lopRepository.Update(request);
            if (result.Success)
            {
                _toastNotification.AddSuccessToastMessage("Lưu dữ liệu thành công!");
            }
            else
            {
                _toastNotification.AddErrorToastMessage("Lưu dữ liệu thất bại!");
            }
            return Ok(result);
        }

        public IActionResult Delete([FromRoute] int id)
        {
            if (id <= 0)
            {
                _toastNotification.AddErrorToastMessage("Vui lòng nhập đầy đủ dữ liệu yêu cầu!!");
                return Ok(new ApiErrorResult<int>());
            }
            var result = _lopRepository.Delete(id);
            if (result.Success)
            {
                _toastNotification.AddSuccessToastMessage("Xóa dữ liệu thành công!");
            }
            else
            {
                _toastNotification.AddErrorToastMessage("Xóa dữ liệu thất bại!");
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

PM_QLHS/Views/Lop/Index.cshtml
@using System.Globalization
@inject Microsoft.Extensions.Configuration.IConfiguration Configuration;
@model PM_QLHS.Models.LopViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Quản lý lớp";
}

<div class="content-wrapper content-wrapper-custom">

    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card card-custom">
                <div class="card-header card-header-custom">
                    <h4 class="card-title">Danh sách lớp</h4>
                    <button type="button" onclick="handleThem()" class="btn btn-primary btn-icon-text btn-fw">
                        <i class="mdi mdi mdi-plus btn-icon-prepend"></i> Thêm
                    </button>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered table-custom">
                            <thead>
                                <tr>
                                    <th>Mã lớp</th>
                                    <th>Tên lớp</th>
                                    <th>Sỉ số</th>
                                    <th>Khối</th>
                                    <th>Giáo viên chủ nhiệm</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model.Lops != null && Model.Lops.Items != null && Model.Lops.Items.Count() > 0)
                                {
                                    @foreach (var patient in Model.Lops.Items)
                                    {
                                        <tr>
                                            <td>@patient.MaLop</td>
                                            <td>@patient.TenLop</td>
                                            <td>@patient.SiSo</td>
                                            <td>@patient.TenKhoi</td>
                                            <td>@patient.HoTen</td>
                                            <td class="btn-group-action">
                                                <button type="button" class="btn btn-primary btn-icon" onclick="handleSua(@patient.MaLop)">
                                                    <i class="mdi mdi-border-color"></i>
                                                </button>
                                                <a class="btn btn-primary btn-icon" asp-controller="Lop" asp-action="Delete" asp-route-id="@patient.MaLop">
                                                    <i class="mdi mdi-delete"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade modal-custom" id="modalLop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="modalLopLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-custom">
            <div class="modal-content">
                <div class="modal-header ">
                    <h5 class="modal-title" id="modalLopLabel" data-type='Create'>Thêm học sinh</h5>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Tên lớp</label>
                                <input type="text" id="txtTenLop" class="form-control" placeholder="Tên lớp">
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Khối</label>
                                <select id="slKhoi" class="js-example-basic-single" style="width:100%">
                                    <option value="">Chọn khối</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Giao viên chủ nhiệm</label>
                                <select id="slGiaoVien" class="js-example-basic-single" style="width:100%">
                                    <option value="">Chọn giáo viên</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Sỉ số</label>
                                <input type="text" id="txtSiSo" class="form-control" placeholder="Sỉ số">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary btn-icon-text btn-fw" data-bs-dismiss="modal">
                        <i class="mdi mdi mdi mdi-close-circle-outline btn-icon-prepend"></i> Đóng
                    </button>
                    <button type="button" onclick="handleSave()" class="btn btn-primary btn-icon-text btn-fw">
                        <i class="mdi mdi  mdi-file-check btn-icon-prepend"></i> Lưu
                    </button>
                </div>
            </div>
        </div>
    </div>
    <script>
        $(document).ready(async function() {
            const dataKhoi = getAllKhoi()
            const dataGV = getAllGVCM()
            const resK = await dataKhoi
            const resGV = await dataGV

            if (resK.data) {
                resK.data.forEach((element) => {
                    $('#slKhoi').append(`<option value="${element.maKhoi}"> ${element.tenKhoi}</option>`);
                });
            }

            if (resGV.data) {
                resGV.data.forEach((element) => {
                    $('#slGiaoVien').append(`<option value="${element.maGiaoVien}"> ${element.hoTen}</option>`);
                });
            }
        });

        function clearData() {
            $('#slKhoi').val('').change();
            $('#slGiaoVien').val('').change();
            $('#txtTenLop').val('')
            $('#txtSiSo').val('')
            document.getElementById('modalLopLabel').setAttribute("data-id", 0)
            document.getElementById('modalLopLabel').setAttribute("data-type", "Create")
        }

        async function getAllKhoi() {
            let dataPromise = new Promise(function(resolve, reject) {
                $.ajax({
                    url: '/Khoi/GetAll',
                    type: "GET",
                    contentType: 'application/json; charset=utf-8',
                    data: {},
                    success: function(data) {
                        //console.log('getAllKhoi', data)
                        return resolve(data)
                    },
                    error: function(err) {
                        return reject(err)
                        alert('error');
                    }
                });
            });
            return dataPromise
        }

        async function getAllGVCM() {
            let dataPromise = new Promise(function(resolve, reject) {
                $.ajax({
                    url: '/giaovien/getallgvcn',
                    type: "GET",
                    contentType: 'application/json; charset=utf-8',
                    data: {},
                    success: function(data) {
                        //console.log('getAllGVCM', data)
                        return resolve(data)
                    },
                    error: function(err) {
                        return reject(err)
                        alert('error');
                    }
                });
            });
            return dataPromise
        }

        async function getLopById(id) {
            let dataPromise = new Promise(function(resolve, reject) {
                $.ajax({
                    type: "GET",
                    url: "/lop/getById",
                    dataType: "json",
                    data: { id: id },
                    success: function(data) {
                        //console.log('getLopById', data)
                        return resolve(data)
                    },
                    error: function(err) {
                        return reject(err)
                        console.log(err);
                    }
                });
            });
            return dataPromise
        }

        async function handleThem() {
            clearData()
            $('#modalLop').modal('show')
        }

        async function handleSua(id) {
            clearData()
            const dataL = getLopById(id)
            const resL = await dataL
            document.getElementById('modalLopLabel').setAttribute("data-type", "Edit")
            document.getElementById('modalLopLabel').setAttribute("data-id", id)
            if (resL.data) {
                let result = resL.data
                //console.log('resL', result)
                $('#slKhoi').val(result.maKhoi).change();
                $('#slGiaoVien').val(result.maGVChuNhiem).change();
                $('#txtTenLop').val(result.tenLop)
                $('#txtSiSo').val(result.siSo)
            }

            $('#modalLop').modal('show')
        }

        function handleSave() {
            var type = document.getElementById('modalLopLabel').getAttribute("data-type")
            var id = document.getElementById('modalLopLabel').getAttribute("data-id")
            let url = type == 'Create' ? '/lop/create' : '/lop/update'
            let method = type == 'Create' ? 'POST' : 'PATCH'
            let params = {
                MaLop: id != 0 ? id : null,
                MaKhoi: $('select[id=slKhoi] option').filter(':selected').val(),
                MaGVChuNhiem: $('select[id=slGiaoVien] option').filter(':selected').val(),
                TenLop: $('#txtTenLop').val(),
                SiSo: $('#txtSiSo').val()
            }
            //console.log('params', params)

            $.ajax({
                type: method,
                url: url,
                dataType: "json",
                data: params,
                success: function(data) {
                    if (data.success) {
                        $('#modalLop').modal('hide');
                        setTimeout(function() {
                            window.location.href = "/Lop/Index";
                        }, 1500);
                    }
                },
                error: function(err) {
                    console.log(err);
                }
            });
        }

    </script>
</div>