PM_QLHS/Models/ThongBaoViewModel.cs
using PM_QLHS.Class.Dtos;
using PM_QLHS.Class.ViewModels;

namespace PM_QLHS.Models
{
    public class ThongBaoViewModel
    {
        public PageReponResult<ThongBaoVm> ThongBaos { get; set; }

        public ThongBaoViewModel()
        {
            ThongBaos = new PageReponResult<ThongBaoVm>();
        }
    }
}

PM_QLHS/Controllers/ThongBaoController.cs
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using PM_QLHS.Class.Authorization;
using PM_QLHS.Class.Dtos;
using PM_QLHS.Class.ViewModels;
using PM_QLHS.Models;
using PM_QLHS.Repository;

namespace PM_QLHS.Controllers
{
    public class ThongBaoController : BaseController
    {
        private readonly ILogger<HocSinhController> _logger;
        private readonly IThongBaoRepository _thongBaoRepository;
        private readonly IToastNotification _toastNotification;

        public ThongBaoController(ILogger<HocSinhController> logger,
            IToastNotification toastNotification,
            IThongBaoRepository thongBaoRepository)
        {
            _logger = logger;
            _toastNotification = toastNotification;
            _thongBaoRepository = thongBaoRepository;
        }

        [Authorize(Role.GVu)]
        public IActionResult Index()
        {
            var data = new ThongBaoViewModel();
            var result = _thongBaoRepository.GetAll();
            data.ThongBaos = result.Success ? result.Data : new PageReponResult<ThongBaoVm>();
            return View(data);
        }

        [HttpGet]
        [Route("/thongbao/getById")]
        public IActionResult GetById(int id)
        {
            var result = _thongBaoRepository.GetById(id);
            return Ok(result);
        }

        [HttpPost]
        [Route("/thongbao/create")]
        public IActionResult Create(ThongBaoVm vm)
        {
            var result = _thongBaoRepository.Create(vm);
            if (result.Success)
            {
                _toastNotification.AddSuccessToastMessage("Lưu dữ liệu thành công!");
            }
            else
            {
                _toastNotification.AddErrorToastMessage("Lưu dữ liệu thất bại!");
            }
            return Ok(result);
        }

        [HttpPatch]
        [Route("/thongbao/update")]
        public IActionResult Update(ThongBaoVm vm)
        {
            if (vm.MaThongBao == null || vm.MaThongBao <= 0)
            {
                _toastNotification.AddErrorToastMessage("Vui lòng nhập đầy đủ dữ liệu yêu cầu!!");
                return Ok(new ApiErrorResult<int>());
            }
            var result = _thongBaoRepository.Update(vm);
            if (result.Success)
            {
                _toastNotification.AddSuccessToastMessage("Lưu dữ liệu thành công!");
            }
            else
            {
                _toastNotification.AddErrorToastMessage("Lưu dữ liệu thất bại!");
            }
            return Ok(result);
        }

        public IActionResult Delete([FromRoute] int id)
        {
            if (id <= 0)
            {
                _toastNotification.AddErrorToastMessage("Vui lòng nhập đầy đủ dữ liệu yêu cầu!!");
                return Ok(new ApiErrorResult<int>());
            }
            var result = _thongBaoRepository.Delete(id);
            if (result.Success)
            {
                _toastNotification.AddSuccessToastMessage("Xóa dữ liệu thành công!");
            }
            else
            {
                _toastNotification.AddErrorToastMessage("Xóa dữ liệu thất bại!");
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

PM_QLHS/Views/ThongBao/Index.cshtml
@using System.Globalization
@inject Microsoft.Extensions.Configuration.IConfiguration Configuration;
@model PM_QLHS.Models.ThongBaoViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Quản lý thông báo";
}

<div class="content-wrapper content-wrapper-custom">

    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card card-custom">
                <div class="card-header card-header-custom">
                    <h4 class="card-title">Danh sách thông báo</h4>
                    <button type="button" onclick="handleThem()" class="btn btn-primary btn-icon-text btn-fw">
                        <i class="mdi mdi mdi-plus btn-icon-prepend"></i> Thêm
                    </button>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered table-custom">
                            <thead>
                                <tr>
                                    <th>Mã thông báo</th>
                                    <th>Tên thông báo</th>
                                    <th>Nội dung</th>
                                    <th>Ngày thông báo</th>
                                    <th>Thao tác</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model.ThongBaos != null && Model.ThongBaos.Items != null && Model.ThongBaos.Items.Count() > 0)
                                {
                                    @foreach (var patient in Model.ThongBaos.Items)
                                    {
                                        <tr>
                                            <td>@patient.MaThongBao</td>
                                            <td>@patient.TenThongBao</td>
                                            <td>@patient.NoiDungThongBao</td>
                                            <td>@patient.NgayThongBao</td>
                                            <td class="btn-group-action">
                                                <button type="button" class="btn btn-primary btn-icon" onclick="handleSua(@patient.MaThongBao)">
                                                    <i class="mdi mdi-border-color"></i>
                                                </button>
                                                <a class="btn btn-primary btn-icon" asp-controller="ThongBao" asp-action="Delete" asp-route-id="@patient.MaThongBao">
                                                    <i class="mdi mdi-delete"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- popup -->
    <div class="modal fade modal-custom" id="modalThongBao" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="modalThongBaoLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-custom">
            <div class="modal-content">
                <div class="modal-header ">
                    <h5 class="modal-title" id="modalThongBaoLabel" data-type='Create'>Thêm/Sửa thông báo</h5>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Tên thông báo</label>
                                <input type="text" id="txtTenThongBao" class="form-control" placeholder="Tên thông báo">
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Nội dung thông báo</label>
                                <textarea id="txtNoiDungThongBao" class="form-control" id="exampleTextarea1" rows="4" placeholder="Nội dung thông báo"></textarea>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary btn-icon-text btn-fw" data-bs-dismiss="modal">
                        <i class="mdi mdi mdi mdi-close-circle-outline btn-icon-prepend"></i> Đóng
                    </button>
                    <button type="button" onclick="handleSave()" class="btn btn-primary btn-icon-text btn-fw">
                        <i class="mdi mdi  mdi-file-check btn-icon-prepend"></i> Lưu
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts {
    <script type="text/javascript">
        $(document).ready(async function () {

        });

        function clearData() {
            $('#txtTenThongBao').val('');
            $('#txtNoiDungThongBao').val('');
            document.getElementById('modalThongBaoLabel').setAttribute("data-id", 0);
            document.getElementById('modalThongBaoLabel').setAttribute("data-type", "Create");
        }

        async function getGVById(id) {
            let dataPromise = new Promise(function (resolve, reject) {
                $.ajax({
                    type: "GET",
                    url: "/thongbao/getById",
                    dataType: "json",
                    data: { id: id },
                    success: function (res) {
                        if (res.success)
                            return resolve(res);
                    },
                    error: function (err) {
                        return reject(err)
                        console.log(err);
                    }
                });
            });
            return dataPromise
        }

        async function handleThem() {
            clearData();
            $('#modalThongBao').modal('show');
        }

        async function handleSua(id) {
            clearData();
            const dataGV = getGVById(id);
            const resGV = await dataGV;
            document.getElementById('modalThongBaoLabel').setAttribute("data-type", "Edit")
            document.getElementById('modalThongBaoLabel').setAttribute("data-id", id)
            if (resGV.data) {
                let result = resGV.data;
                $('#txtTenThongBao').val(result.tenThongBao);
                $('#txtNoiDungThongBao').val(result.noiDungThongBao);
            }

            $('#modalThongBao').modal('show');
        }

        function handleSave() {
            var type = document.getElementById('modalThongBaoLabel').getAttribute("data-type")
            var id = document.getElementById('modalThongBaoLabel').getAttribute("data-id")
            let url = type == 'Create' ? '/thongbao/create' : '/thongbao/update'
            let method = type == 'Create' ? 'POST' : 'PATCH'
            let params = {
                MaThongBao: id != 0 ? id : null,
                TenThongBao: $('#txtTenThongBao').val(),
                NoiDungThongBao: $('#txtNoiDungThongBao').val()
            }
            //console.log('params', params);
            $.ajax({
                type: method,
                url: url,
                dataType: "json",
                data: params,
                success: function (data) {
                    if (data.success) {
                        $('#modalThongBao').modal('hide');
                        setTimeout(function () {
                            window.location.href = "/ThongBao/Index";
                        }, 1500);
                    }
                },
                error: function (err) {
                    console.log(err);
                }
            });
        }
    </script>
}