PM_QLHS/Models/QuyDinhViewModel.cs
using PM_QLHS.Class.Dtos;
using PM_QLHS.Class.ViewModels;

namespace PM_QLHS.Models
{
    public class QuyDinhViewModel
    {
        public PageReponResult<QuyDinhVm> QuyDinhs { get; set; }

        public QuyDinhViewModel()
        {
            QuyDinhs = new PageReponResult<QuyDinhVm>();
        }
    }
}

PM_QLHS/Controllers/QuyDinhController.cs
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using PM_QLHS.Class.Authorization;
using PM_QLHS.Class.Dtos;
using PM_QLHS.Class.ViewModels;
using PM_QLHS.Models;
using PM_QLHS.Repository;

namespace PM_QLHS.Controllers
{
    public class QuyDinhController : BaseController
    {
        private readonly ILogger<HocSinhController> _logger;
        private readonly IQuyDinhRepository _quyDinhRepository;
        private readonly IToastNotification _toastNotification;

        public QuyDinhController(ILogger<HocSinhController> logger,
            IToastNotification toastNotification,
            IQuyDinhRepository quyDinhRepository)
        {
            _logger = logger;
            _toastNotification = toastNotification;
            _quyDinhRepository = quyDinhRepository;
        }

        [Authorize(Role.BGH)]
        public IActionResult Index()
        {
            var data = new QuyDinhViewModel();
            var result = _quyDinhRepository.GetAll();
            data.QuyDinhs = result.Success ? result.Data : new PageReponResult<QuyDinhVm>();
            return View(data);
        }

        [HttpGet]
        [Route("/quydinh/getById")]
        public IActionResult GetById(int id)
        {
            var result = _quyDinhRepository.GetById(id);
            return Ok(result);
        }

        [HttpPost]
        [Route("/quydinh/create")]
        public IActionResult Create(QuyDinhVm vm)
        {
            var result = _quyDinhRepository.Create(vm);
            if (result.Success)
            {
                _toastNotification.AddSuccessToastMessage("Lưu dữ liệu thành công!");
            }
            else
            {
                _toastNotification.AddErrorToastMessage("Lưu dữ liệu thất bại!");
            }
            return Ok(result);
        }

        [HttpPatch]
        [Route("/quydinh/update")]
        public IActionResult Update(QuyDinhVm vm)
        {
            if (vm.MaQuyDinh == null || vm.MaQuyDinh <= 0)
            {
                _toastNotification.AddErrorToastMessage("Vui lòng nhập đầy đủ dữ liệu yêu cầu!!");
                return Ok(new ApiErrorResult<int>());
            }
            var result = _quyDinhRepository.Update(vm);
            if (result.Success)
            {
                _toastNotification.AddSuccessToastMessage("Lưu dữ liệu thành công!");
            }
            else
            {
                _toastNotification.AddErrorToastMessage("Lưu dữ liệu thất bại!");
            }
            return Ok(result);
        }

        public IActionResult Delete([FromRoute] int id)
        {
            if (id <= 0)
            {
                _toastNotification.AddErrorToastMessage("Vui lòng nhập đầy đủ dữ liệu yêu cầu!!");
                return Ok(new ApiErrorResult<int>());
            }
            var result = _quyDinhRepository.Delete(id);
            if (result.Success)
            {
                _toastNotification.AddSuccessToastMessage("Xóa dữ liệu thành công!");
            }
            else
            {
                _toastNotification.AddErrorToastMessage("Xóa dữ liệu thất bại!");
            }
            return RedirectToAction(nameof(Index));
        }

    }
}

PM_QLHS/Views/QuyDinh/Index.cshtml
@using System.Globalization
@inject Microsoft.Extensions.Configuration.IConfiguration Configuration;
@model PM_QLHS.Models.QuyDinhViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Quản lý quy định";
}

<div class="content-wrapper content-wrapper-custom">

    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card card-custom">
                <div class="card-header card-header-custom">
                    <h4 class="card-title">Danh sách quy định</h4>
                    <button type="button" onclick="handleThem()" class="btn btn-primary btn-icon-text btn-fw">
                        <i class="mdi mdi mdi-plus btn-icon-prepend"></i> Thêm
                    </button>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered table-custom">
                            <thead>
                                <tr>
                                    <th>Mã quy định</th>
                                    <th>Tên quy định</th>
                                    <th>Nội dung</th>
                                    <th>Thao tác</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model.QuyDinhs != null && Model.QuyDinhs.Items != null && Model.QuyDinhs.Items.Count() > 0)
                                {
                                    @foreach (var patient in Model.QuyDinhs.Items)
                                    {
                                        <tr>
                                            <td>@patient.MaQuyDinh</td>
                                            <td>@patient.TenQuyDinh</td>
                                            <td>@patient.NoiDungQuyDinh</td>
                                            <td class="btn-group-action">
                                                <button type="button" class="btn btn-primary btn-icon" onclick="handleSua(@patient.MaQuyDinh)">
                                                    <i class="mdi mdi-border-color"></i>
                                                </button>
                                                <a class="btn btn-primary btn-icon" asp-controller="QuyDinh" asp-action="Delete" asp-route-id="@patient.MaQuyDinh">
                                                    <i class="mdi mdi-delete"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- popup -->
    <div class="modal fade modal-custom" id="modalQuyDinh" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="modalQuyDinhLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-custom">
            <div class="modal-content">
                <div class="modal-header ">
                    <h5 class="modal-title" id="modalQuyDinhLabel" data-type='Create'>Thêm/Sửa quy định</h5>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Tên quy định</label>
                                <input type="text" id="txtTenQuyDinh" class="form-control" placeholder="Tên quy định">
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Nội dung quy định</label>
                                <textarea id="txtNoiDungQuyDinh" class="form-control" id="exampleTextarea1" rows="4" placeholder="Nội dung quy định"></textarea>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary btn-icon-text btn-fw" data-bs-dismiss="modal">
                        <i class="mdi mdi mdi mdi-close-circle-outline btn-icon-prepend"></i> Đóng
                    </button>
                    <button type="button" onclick="handleSave()" class="btn btn-primary btn-icon-text btn-fw">
                        <i class="mdi mdi  mdi-file-check btn-icon-prepend"></i> Lưu
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts {
    <script type="text/javascript">
        $(document).ready(async function () {

        });

        function clearData() {
            $('#txtTenQuyDinh').val('');
            $('#txtNoiDungQuyDinh').val('');
            document.getElementById('modalQuyDinhLabel').setAttribute("data-id", 0);
            document.getElementById('modalQuyDinhLabel').setAttribute("data-type", "Create");
        }

        async function getGVById(id) {
            let dataPromise = new Promise(function (resolve, reject) {
                $.ajax({
                    type: "GET",
                    url: "/quydinh/getById",
                    dataType: "json",
                    data: { id: id },
                    success: function (res) {
                        if (res.success)
                            return resolve(res);
                    },
                    error: function (err) {
                        return reject(err)
                        console.log(err);
                    }
                });
            });
            return dataPromise
        }

        async function handleThem() {
            clearData();
            $('#modalQuyDinh').modal('show');
        }

        async function handleSua(id) {
            clearData();
            const dataGV = getGVById(id);
            const resGV = await dataGV;
            document.getElementById('modalQuyDinhLabel').setAttribute("data-type", "Edit")
            document.getElementById('modalQuyDinhLabel').setAttribute("data-id", id)
            if (resGV.data) {
                let result = resGV.data;
                $('#txtTenQuyDinh').val(result.tenQuyDinh);
                $('#txtNoiDungQuyDinh').val(result.noiDungQuyDinh);
            }

            $('#modalQuyDinh').modal('show');
        }

        function handleSave() {
            var type = document.getElementById('modalQuyDinhLabel').getAttribute("data-type")
            var id = document.getElementById('modalQuyDinhLabel').getAttribute("data-id")
            let url = type == 'Create' ? '/quydinh/create' : '/quydinh/update'
            let method = type == 'Create' ? 'POST' : 'PATCH'
            let params = {
                MaQuyDinh: id != 0 ? id : null,
                TenQuyDinh: $('#txtTenQuyDinh').val(),
                NoiDungQuyDinh: $('#txtNoiDungQuyDinh').val()
            }
            //console.log('params', params);
            $.ajax({
                type: method,
                url: url,
                dataType: "json",
                data: params,
                success: function (data) {
                    if (data.success) {
                        $('#modalQuyDinh').modal('hide');
                        setTimeout(function () {
                            window.location.href = "/QuyDinh/Index";
                        }, 1500);
                    }
                },
                error: function (err) {
                    console.log(err);
                }
            });
        }
    </script>
}