PM_QLHS/Models/HocSinhViewModel.cs
using PM_QLHS.Class.Dtos;

namespace PM_QLHS.Models
{
    public class HocSinhViewModel
    {
        public int MaHocSinh { get; set; }
        public int? MaLop { get; set; }
        public int? MaTaiKhoan { get; set; }
        public string? HoTen { get; set; }
        public DateTime? NgaySinh { get; set; }
        public bool? GioiTinh { get; set; }
        public string? Email { get; set; }
        public string? DiaChi { get; set; }
        public string? TenLop { get; set; }
        public PageReponResult<HocSinhViewModel> HocSinhs { get; set; }

        public HocSinhViewModel()
        {
            HocSinhs = new PageReponResult<HocSinhViewModel>();
        }
    }
}

PM_QLHS/Controllers/HocSinhController.cs
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using PM_QLHS.Class.Authorization;
using PM_QLHS.Class.Dtos;
using PM_QLHS.Class.ViewModels;
using PM_QLHS.Models;
using PM_QLHS.Repository;
using System.Data;
using System.Diagnostics;

namespace PM_QLHS.Controllers
{
    public class HocSinhController : BaseController
    {
        private readonly ILogger<HocSinhController> _logger;
        private readonly IHocSinhRepository _hocSinhRepository;
        private readonly IToastNotification _toastNotification;

        public HocSinhController(ILogger<HocSinhController> logger, IToastNotification toastNotification, IHocSinhRepository hocSinhRepository)
        {
            _logger = logger;
            _toastNotification = toastNotification;
            _hocSinhRepository = hocSinhRepository;
        }

        [Authorize(Role.GVu)]
        public IActionResult Index()
        {
            var data = new HocSinhViewModel();
            var result = _hocSinhRepository.GetAllView("");
            data.HocSinhs = result.Success ? result.Data : new PageReponResult<HocSinhViewModel>();
            return View(data);
        }

        [HttpPost]
        public IActionResult Index(HocSinhVm request)
        {
            var data = new HocSinhViewModel();
            var result = _hocSinhRepository.GetAllView(request.HoTen);
            data.HocSinhs = result.Success ? result.Data : new PageReponResult<HocSinhViewModel>();
            return View(data);
        }

        [HttpGet]
        public ActionResult GetALl()
        {
            var result = _hocSinhRepository.GetAll();
            return Json(result);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpPost]
        [Route("/hocsinh/create")]
        public IActionResult Create(HocSinhVm request)
        {
            var result = _hocSinhRepository.Create(request);

            if (result.Success)
            {
                _toastNotification.AddSuccessToastMessage("Lưu dữ liệu thành công!");
            }
            else
            {
                _toastNotification.AddErrorToastMessage("Lưu dữ liệu thất bại!");
            }
            return Ok(result);
        }

        [HttpPatch]
        [Route("/hocsinh/update")]
        public IActionResult Update(HocSinhVm request)
        {
            if (request.MaHocSinh <= 0)
            {
                _toastNotification.AddErrorToastMessage("Vui lòng nhập đầy đủ dữ liệu yêu cầu!!");
                return Ok(new ApiErrorResult<int>());
            }
            var result = _hocSinhRepository.Update(request);
            if (result.Success)
            {
                _toastNotification.AddSuccessToastMessage("Lưu dữ liệu thành công!");
            }
            else
            {
                _toastNotification.AddErrorToastMessage("Lưu dữ liệu thất bại!");
            }
            return Ok(result);
        }

        public IActionResult Delete([FromRoute] int id)
        {
            if (id <= 0)
            {
                _toastNotification.AddErrorToastMessage("Vui lòng nhập đầy đủ dữ liệu yêu cầu!!");
                return Ok(new ApiErrorResult<int>());
            }
            var result = _hocSinhRepository.Delete(id);
            if (result.Success)
            {
                _toastNotification.AddSuccessToastMessage("Xóa dữ liệu thành công!");
            }
            else
            {
                _toastNotification.AddErrorToastMessage("Xóa dữ liệu thất bại!");
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        [Route("/hocsinh/getById")]
        public IActionResult GetById(int id)
        {
            var result = _hocSinhRepository.GetById(id);
            return Json(result);
        }
    }
}

PM_QLHS/Views/HocSinh/Index.cshtml
@using System.Globalization
@inject Microsoft.Extensions.Configuration.IConfiguration Configuration;
@model PM_QLHS.Models.HocSinhViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Quản lý học sinh";
}

<div class="content-wrapper content-wrapper-custom">

    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card card-custom">
                <div class="card-header" style="padding-top: 10px; padding-bottom: 10px;">
                    <form action="/HocSinh/Index" method="post">
                        <div class="form-group row" style="margin-bottom: 0;">
                            <div class="col">
                                <label>Họ tên</label>
                                <input type="text" id="txtSearchHoTen" asp-for="HoTen" class="form-control" placeholder="Họ tên">
                            </div>
                            <div class="col">
                                <button type="submit" class="btn btn-primary btn-icon-text btn-fw" style="margin-top: 25px;">
                                    <i class="mdi mdi mdi-filter-outline btn-icon-prepend"></i> Tìm kiếm
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card card-custom">
                <div class="card-header card-header-custom">
                    <h4 class="card-title">Danh sách học sinh</h4>
                    <button type="button" onclick="handleThem()" class="btn btn-primary btn-icon-text btn-fw">
                        <i class="mdi mdi mdi-plus btn-icon-prepend"></i> Thêm
                    </button>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered table-custom">
                            <thead>
                                <tr>
                                    <th>Mã học sinh</th>
                                    <th>Tên học sinh</th>
                                    <th>Tên lớp</th>
                                    <th>Ngày sinh</th>
                                    <th>Giới tính</th>
                                    <th>Địa chỉ</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model.HocSinhs != null && Model.HocSinhs.Items != null && Model.HocSinhs.Items.Count() > 0)
                                {
                                    @foreach (var patient in Model.HocSinhs.Items)
                                    {
                                        <tr>
                                            <td>@patient.MaHocSinh</td>
                                            <td>@patient.HoTen</td>
                                            <td>@patient.TenLop</td>
                                            <td>@(patient.NgaySinh != null ? patient.NgaySinh?.ToString("dd/MM/yyyy") : "")</td>
                                            <td>@((patient.GioiTinh != null && patient.GioiTinh == true) ? "Nữ" : "Nam")</td>
                                            <td>@patient.DiaChi</td>
                                            <td class="btn-group-action">
                                                <button type="button" class="btn btn-primary btn-icon" onclick="handleSua(@patient.MaHocSinh)">
                                                    <i class="mdi mdi-border-color"></i>
                                                </button>
                                                <a class="btn btn-primary btn-icon" asp-controller="HocSinh" asp-action="Delete" asp-route-id="@patient.MaHocSinh">
                                                    <i class="mdi mdi-delete"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade modal-custom" id="modalHocSinh" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="modalHocSinhLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-custom">
            <div class="modal-content">
                <div class="modal-header ">
                    <h5 class="modal-title" id="modalHocSinhLabel" data-type='Create'>Thêm học sinh</h5>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Họ tên</label>
                                <input type="text" id="txtHoTen" class="form-control" placeholder="Họ tên">
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Lớp</label>
                                <select id="slLop" class="js-example-basic-single" style="width:100%">
                                    <option value="">Chọn lớp</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Ngày sinh</label>
                                <input type="date" id="txtNgaySinh" class="form-control">
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group row">
                                <label>Giới tính</label>
                                <div class="col-lg-2">
                                    <div class="form-check">
                                        <label class="form-check-label">
                                            <input type="radio" class="form-check-input" name="GioiTinh" id="radNam" value="0" checked> Nam
                                        </label>
                                    </div>
                                </div>
                                <div class="col-lg-2">
                                    <div class="form-check">
                                        <label class="form-check-label">
                                            <input type="radio" class="form-check-input" name="GioiTinh" id="radNu" value="1"> Nữ
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Email</label>
                                <input type="email" id="txtEmail" class="form-control" placeholder="Email">
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Địa chỉ</label>
                                <input type="text" id="txtDiaChi" class="form-control" placeholder="Địa chỉ">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary btn-icon-text btn-fw" data-bs-dismiss="modal">
                        <i class="mdi mdi mdi mdi-close-circle-outline btn-icon-prepend"></i> Đóng
                    </button>
                    <button type="button" onclick="handleSave()" class="btn btn-primary btn-icon-text btn-fw">
                        <i class="mdi mdi  mdi-file-check btn-icon-prepend"></i> Lưu
                    </button>
                </div>
            </div>
        </div>
    </div>


</div>
@section scripts {
    <script type="text/javascript">
        $(document).ready(async function () {
            const dataLop = getAllLop()
            const resL = await dataLop

            if (resL.data) {
                resL.data.forEach((element) => {
                    $('#slLop').append(`<option value="${element.maLop}"> ${element.tenLop}</option>`);
                });
            }
        });

        function clearData() {
            $('#slLop').val('').change();
            $('#txtHoTen').val('')
            $('#txtNgaySinh').val(null)
            $('#txtEmail').val('')
            $('#txtDiaChi').val('')
            $('input[name="GioiTinh"][value="0"]').prop('checked', true);
            document.getElementById('modalHocSinhLabel').setAttribute("data-id", 0)
            document.getElementById('modalHocSinhLabel').setAttribute("data-type", "Create")
        }

        async function getAllLop() {
            let dataPromise = new Promise(function (resolve, reject) {
                $.ajax({
                    url: '/Lop/GetAll',
                    type: "GET",
                    contentType: 'application/json; charset=utf-8',
                    data: {},
                    success: function (data) {
                        //console.log('getAllLop', data)
                        return resolve(data)
                    },
                    error: function (err) {
                        return reject(err)
                        alert('error');
                    }
                });
            });
            return dataPromise
        }

        async function getHSById(id) {
            let dataPromise = new Promise(function (resolve, reject) {
                $.ajax({
                    type: "GET",
                    url: "/hocsinh/getById",
                    dataType: "json",
                    data: { id: id },
                    success: function (data) {
                        //console.log('getHSById', data)
                        return resolve(data)
                    },
                    error: function (err) {
                        return reject(err)
                        console.log(err);
                    }
                });
            });
            return dataPromise
        }

        async function handleThem() {
            clearData()
            $('#modalHocSinh').modal('show')
        }

        async function handleSua(id) {
            clearData()
            const dataHS = getHSById(id)
            const resHS = await dataHS
            document.getElementById('modalHocSinhLabel').setAttribute("data-type", "Edit")
            document.getElementById('modalHocSinhLabel').setAttribute("data-id", id)
            if (resHS.data) {
                let result = resHS.data
                let gt = result.gioiTinh ? '1' : '0'
                //console.log('resHS', result)
                $('#slLop').val(result.maLop).change();
                $('#txtHoTen').val(result.hoTen)
                $('#txtNgaySinh').val(moment(result.ngaySinh).format("YYYY-MM-DD"))
                $('#txtEmail').val(result.email)
                $('#txtDiaChi').val(result.diaChi)
                $('input[name="GioiTinh"][value="' + gt + '"]').prop('checked', true);
            }

            $('#modalHocSinh').modal('show')
        }

        function handleSave() {
            var type = document.getElementById('modalHocSinhLabel').getAttribute("data-type")
            var id = document.getElementById('modalHocSinhLabel').getAttribute("data-id")
            let url = type == 'Create' ? '/hocsinh/create' : '/hocsinh/update'
            let method = type == 'Create' ? 'POST' : 'PATCH'
            let params = {
                MaHocSinh: id != 0 ? id : null,
                MaLop: $('select[id=slLop] option').filter(':selected').val(),
                HoTen: $('#txtHoTen').val(),
                NgaySinh: $('#txtNgaySinh').val(),
                GioiTinh: $("input[type='radio'][name='GioiTinh']:checked").val() == "1" ? true : false,
                Email: $('#txtEmail').val(),
                DiaChi: $('#txtDiaChi').val(),
            }
            //console.log('params', params)

            $.ajax({
                type: method,
                url: url,
                dataType: "json",
                data: params,
                success: function (data) {
                    if (data.success) {
                        $('#modalLop').modal('hide');
                        setTimeout(function() {
                            window.location.href = "/HocSinh/Index";
                        }, 1500);
                    }
                },
                error: function (err) {
                    console.log(err);
                }
            });
        }

    </script>
}